### ISSUE TITLE
All the images are broken

### ISSUE THREAD

**Issue by yarons** [briangann/grafana-sensu-datasource#1]
It makes it difficult to understand the explanations about adding Sensu source.

Thank you.

**Comment by briangann** [comment]
This datasource isn't quite ready for use - still a work in progress :)  Once it's good to go I'll ask for it to be added to grafana.net.

**Comment by yarons** [comment]
Great, thanks, can I help?
I'm guessing it's based on the Sensu API?

**Comment by briangann** [comment]
It is based on the Sensu API, and it really just needs to be tested thoroughly.  I'm only actively using the "events" and "aggregate" options, the rest are not well-tested.  Any help would be great :)

**Comment by yarons** [comment]
I tried installing the plugin, maybe I did it wrong since I couldn't see the events, clients and aggregate functions, am I doing something wrong?

**Comment by yarons** [comment]
I tried installing the plugin, maybe I did it wrong since I couldn't see the events, clients and aggregate functions in the autocomplete, am I doing something wrong?

**Comment by briangann** [comment]
I fixed the paths that were hardcoded in the plugin, I have sensu behind nginx and didn't realize the path was still in there.

You should be able to just set the datasource url to be http://192.168.1.33:4567  (where your sensu-api service is running, typically port 4567)

This is still a work in progress, but it will display events/aggregates/client history.  The "results" option isn't returning enough data to make it useful.

**Comment by briangann** [comment]
Docs and screenshots are now accurate. The "results" option is now returning good data too.
