### ISSUE TITLE
Failed to add data source

### ISSUE THREAD

**Issue by sjthespian** [briangann/grafana-sensu-datasource#6]
@briangann I have tried cloning this repo into both my base plugins directory and plugins/datasource, but in both cases adding a Sense datasource throws the error:
```
Plugin Error
Fetch error: 404 Not Found Instantiating https://www.myhost.org/grafana/public/app/plugins/datasource/briangann-sensu-datasource/module Loading app/plugins/datasource/briangann-sensu-datasource/module
```
Changing the name of the cloned directory to `briangann-sensu-datasource` doesn't change the error.

The only thing I see in grafana.log is the 404 for that path.

Any idea what is going on?

**Comment by briangann** [comment]
you need to clone it into /var/lib/grafana/plugins/briangann-sensu-datasource and restart grafana-server for it to show up.

If it still gives an error, can you pull up chrome developer tools and screenshot the network tab's error output?

**Comment by sjthespian** [comment]
It's a slightly different path (this is on a FreeBSD server), so it ends up in /usr/local/share/grafana/public/app/plugins/datasource/briangann-sensu-datasource.

There's' nothing interesting in the developer tools, I just see it trying to request `/grafana/public/app/plugins/datasource/briangann-sensu-datasource` which throws a 404.

<img width="994" alt="screen shot 2018-04-09 at 8 49 42 am" src="https://user-images.githubusercontent.com/1789285/38508278-9ea2933c-3bd3-11e8-9613-c8a62bc2472f.png">

**Comment by briangann** [comment]
can you check what your /etc/grafana/grafana.ini files says for plugins?

the default location for new plugins go into a different location than the grafana installation (it doesn't search there)

usually it's commented out, and defaults to **/var/lib/grafana/plugins**
```
#
# Directory where grafana will automatically scan and look for plugins
#
;plugins = /var/lib/grafana/plugins
```

When you install another plugin with **grafana-cli** where do they end up?

the builtin datasources are found in the grafana installation (on ubuntu its here)

```
[root@ip-172-31-33-151 /]# ls -l /usr/share/grafana/public/app/plugins/datasource
total 44
drwxr-xr-x 5 root root 4096 Mar 25 07:09 cloudwatch
drwxr-xr-x 5 root root 4096 Mar 25 07:09 elasticsearch
drwxr-xr-x 3 root root 4096 Mar 25 07:09 grafana
drwxr-xr-x 3 root root 4096 Mar 25 07:09 grafana-live
drwxr-xr-x 6 root root 4096 Mar 25 07:09 graphite
drwxr-xr-x 5 root root 4096 Mar 25 07:09 influxdb
drwxr-xr-x 2 root root 4096 Mar 25 07:09 mixed
drwxr-xr-x 5 root root 4096 Mar 25 07:09 mysql
drwxr-xr-x 5 root root 4096 Mar 25 07:09 opentsdb
drwxr-xr-x 5 root root 4096 Mar 25 07:09 postgres
drwxr-xr-x 7 root root 4096 Mar 25 07:09 prometheus
```

**Comment by briangann** [comment]
this plugin is going to be in the grafana official plugin repo soon, so the cli installation will work and make this easier to keep up to date.

**Comment by sjthespian** [comment]
Whoever wrote the FreeBSD port decided s/he didn't like the existing paths, so have moved things all over the system (in some cases to match the standard FreeBSD layout) -- even to the point of using grafana.conf instead of grafana.ini.  And guess what, that's the problem!  I put the plugin in the plugins directory that is part of the app (/usr/local/share/grafana/public/app/plugins/datasource) while grafana.conf is configured for /var/db/grafana. I just moved it there and now it's loading fine.

Feel free to close the issue and I'll go back to beating my head on the wall.... thanks for the help and what looks like a *great* plugin!
