### ISSUE TITLE
Debugging output? 

### ISSUE THREAD

**Issue by standaloneSA** [briangann/grafana-sensu-datasource#8]
I'm having trouble getting this talking to my sensu installation, and I also am having trouble getting debugging information to figure out what the problem is... Any tips on increasing verbosity of logging?

**Comment by briangann** [comment]
The best method is to pull up chrome developer tools and look at what the network traffic is doing.

Grafana needs to be able to talk to the sensu api.  My setup has it reverse-proxied with nginx with settings like this:

![image](https://user-images.githubusercontent.com/7364245/48265049-18f2f800-e3f1-11e8-9812-d76546f17ea0.png)

nginx config looks like this
```
upstream sensuapi {
  server 184.186.29.164:9094;
  keepalive 32;
}

location /sensu-api/ {
      proxy_pass http://sensuapi;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $http_host;
      rewrite ^/sensu-api/sensu/(.*) /$1 break;
      rewrite ^/sensu-api/(.*) /$1 break;
  }
```

**Comment by standaloneSA** [comment]
Cool, thanks. I ended up getting it working. I wasn't the one who spun up the Sensu instance, and it turns out I was trying to talk to the Uchiwa API rather than the Sensu API. Got that resolved and it works like a charm. Thanks!
